# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Flatcar doesn't have python installed, so we need to install ActivePython3 at first
- name: "Installing python3 on Flatcar VM {{ vm_name }}"
  ansible.builtin.script: "./install_python3.sh '{{ flatcar_python3_download_url }}'"
  register: ap3_install_result
  delegate_to: "{{ vm_guest_ip }}"

- name: "Display the result of python install"
  ansible.builtin.debug: var=ap3_install_result

- name: "Get python path in flatcar"
  ansible.builtin.shell: which python
  delegate_to: "{{ vm_guest_ip }}"
  register: python3_path_result

- name: "Update VM's python path to in-memory inventory"
  when:
    - python3_path_result.stdout is defined
    - python3_path_result.stdout | length > 0
  block:
    - name: "Reset vm_python for flatcar"
      ansible.builtin.set_fact:
        vm_python: "{{ python3_path_result.stdout }}"

    - name: "Update python path in memory inventory"
      include_tasks: ../../../common/add_host_in_memory_inventory.yml
      vars:
        add_host_in_memory_inventory_ip: "{{ vm_guest_ip }}"
        add_host_in_memory_inventory_gp: "target_vm"
        add_host_in_memory_inventory_user: "{{ vm_username }}"
        add_host_in_memory_inventory_pwd: "{{ vm_password }}"
        add_host_in_memory_inventory_python: "{{ vm_python }}"
        add_host_in_memory_inventory_ssh_pipeline: "{{ vm_ssh_pipeline_enable | default(false) }}"

- name: "Check /etc/ssh/sshd_config status"
  include_tasks: ../../utils/get_file_stat_info.yml
  vars:
    guest_file_path: "/etc/ssh/sshd_config"

# The original /etc/ssh/sshd_config on Flatcar is a symbolic link
- name: "Convert /etc/ssh/sshd_config from symbolic link to regular file"
  ansible.builtin.shell: sed -i '' /etc/ssh/sshd_config
  become: true
  delegate_to: "{{ vm_guest_ip }}"
  when: guest_file_stat.islnk | default(false)

- name: "Permit root login through ssh"
  include_tasks: ../../utils/replace_or_add_line_in_file.yml
  vars:
    file: "/etc/ssh/sshd_config"
    reg_exp: "^#?PermitRootLogin"
    line_content: "PermitRootLogin yes"
