# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get WSL default version after WSL install"
  include_tasks: get_wsl_default_version.yml

- name: "Save the WSL default version after install"
  ansible.builtin.set_fact:
    wsl_default_version_original: "{{ wsl_default_version }}"

# Here setting WSL version to 2 only when version 1 is detected above
- name: "Set the WSL default version to 2 from 1"
  when: wsl_default_version_original | int == 1
  block:
    - name: "Set the WSL default version to 2 in guest OS"
      include_tasks: ../utils/win_execute_cmd.yml
      vars:
        win_powershell_cmd: >-
          $result = wsl.exe --set-default-version 2;
          $clean_result = $result -replace '\u0000','';
          Write-host $clean_result
    - name: "Get WSL default version after setting to 2"
      include_tasks: get_wsl_default_version.yml

- name: "Check the default version is WSL 2"
  ansible.builtin.assert:
    that:
      - (wsl_default_version_original | int == 2) or (wsl_default_version | int == 2)
    fail_msg: >-
      Neither the original WSL default version '{{ wsl_default_version_original }}'
      nor the version after setting '{{ wsl_default_version }}' matches the required version 2.
