# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get installed WSL version info"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      $result = wsl.exe --version;
      $clean_result = $result -replace '\u0000','';
      Write-host $clean_result
    win_execute_cmd_ignore_error: true

- name: "Get installed WSL status"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      $result = wsl.exe --status;
      $clean_result = $result -replace '\u0000','';
      Write-host $clean_result
    win_execute_cmd_ignore_error: true

- name: "Check the default version is WSL 2"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.rc is defined
      - win_powershell_cmd_output.rc == 0
      - win_powershell_cmd_output.stdout is defined
      - win_powershell_cmd_output.stdout is search("Default Version:\ 2")
    fail_msg: >-
      Failed to get the default version WSL 2 in the output of command 'wsl.exe --status':
      '{{ win_powershell_cmd_output.stdout | default('') }}'.
