# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Install WSL distribution"
  ansible.windows.win_shell: >-
    $result = wsl.exe --install {{ wsl_distribution_name }};
    $clean_result = $result -replace '\u0000','';
    Write-host $clean_result
  delegate_to: "{{ vm_guest_ip }}"
  register: wsl_distro_install_result
  ignore_errors: true
  async: 600
  poll: 0

- name: "Retry to list installed WSL distribution"
  ansible.windows.win_shell: >-
    $result = wsl.exe --list;
    $clean_result = $result -replace '\u0000','';
    Write-host $clean_result
  register: list_wsl_distro_result
  ignore_errors: true
  delegate_to: "{{ vm_guest_ip }}"
  ignore_unreachable: true
  until:
    - list_wsl_distro_result.rc is defined
    - list_wsl_distro_result.rc == 0
    - list_wsl_distro_result.stdout is defined
    - list_wsl_distro_result.stdout | length != 0
  retries: 20
  delay: 30

- name: "Check WSL distribution is listed"
  ansible.builtin.assert:
    that:
      - list_wsl_distro_result.rc is defined
      - list_wsl_distro_result.rc == 0
      - list_wsl_distro_result.stdout is defined
      - list_wsl_distro_result.stdout is search(wsl_distribution_name)
    fail_msg: >-
      List WSL distribution command 'wsl.exe --list' failed or distribution '{{ wsl_distribution_name }}'
      is not listed in the command output '{{ list_wsl_distro_result.stdout | default('') }}'.

- name: "Pause 10 seconds after distribution install"
  ansible.builtin.pause:
    seconds: 10

- name: "Restart the guest OS"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
