# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Unregister the installed WSL distribution"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      $result = wsl.exe --unregister {{ wsl_distribution_name }};
      $clean_result = $result -replace '\u0000','';
      Write-host $clean_result

- name: "Pause 10 seconds after distribution unregister"
  ansible.builtin.pause:
    seconds: 10

- name: "Get WSL distribution status after unregister"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      $result = wsl.exe --list;
      $clean_result = $result -replace '\u0000','';
      Write-host $clean_result
    win_execute_cmd_ignore_error: true

- name: "Check there is no WSL distribution after unregister"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.rc is defined
      - win_powershell_cmd_output.rc == 0
      - win_powershell_cmd_output.stdout is defined
      - win_powershell_cmd_output.stdout is search("has no installed distributions")
    fail_msg: >-
      List WSL distribution failed after executing unregister WSL distribution
      '{{ wsl_distribution_name }}' command or not found key string 'has no installed distributions'
      in the output '{{ win_powershell_cmd_output.stdout | default('') }}'.
