# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is for WSL 2 and Linux distribution installation testing
# in Windoows guest OS.
# The Windows Subsystem for Linux (WSL) is available for installation on:
# 1. Windows Server 2019 (version 1709) and later
#    https://docs.microsoft.com/en-us/windows/wsl/install-on-server
# 2. Windows 10 version 2004 and higher (Build 19041 and higher) or Windows 11
#    https://docs.microsoft.com/en-us/windows/wsl/install
#
- name: wsl_distro_install_uninstall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because nested virtualization is not supported
              on ESXi on ARM.
            skip_reason: "Not Supported"
          when: esxi_cpu_vendor == 'arm'

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "WSL is not supported by {{ guest_os_ansible_distribution }} with build number {{ guest_os_build_num }} "
            skip_reason: "Not Supported"
          when: >
            (guest_os_ansible_distribution_major_ver | int < 10) or
            (guest_os_product_type == 'server' and guest_os_build_num | int < 16299) or
            (guest_os_product_type == 'client' and guest_os_build_num | int < 19041)

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "There is known issue of WSL installation in Windows Server Core, please refer to this issue https://github.com/microsoft/WSL/issues/10008, will add Windows Server Core support after this issue is resolved."
            skip_reason: "Not Supported"
          when:
            - guest_os_installation_type == "Server Core"

        # By default downloading the latest version of WSL from github,
        # or set this parameter 'wsl_install_source' to 'cmd' to install
        # through 'wsl.exe' command in guest OS.
        - name: "Set fact of the WSL install source"
          ansible.builtin.set_fact:
            wsl_install_source: "github"

        - name: "Prepare WSL testing"
          include_tasks: wsl_test_prepare.yml

        - name: "Install WSL via 'wsl.exe' tool"
          include_tasks: install_wsl_via_cmd.yml
          when: wsl_install_source == "cmd"

        - name: "Install WSL via downloaded MSI from github"
          include_tasks: install_wsl_via_msi.yml
          when: wsl_install_source == "github"

        - name: "Check default WSL version 2"
          include_tasks: check_wsl_version.yml

        - name: "Install WSL distribution"
          include_tasks: install_wsl_distro.yml

        - name: "Check WSL distribution"
          include_tasks: check_wsl_distro.yml

        - name: "Uninstall WSL distribution"
          include_tasks: unregister_wsl_distro.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
