# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Start a listening service on server VM for RDMA ping-pong test
#
- name: "Set command for starting a listening process on server VM"
  ansible.builtin.set_fact:
    pvrdma_server_start_cmd: "rping -s -a {{ pvrdma_server_vm_ipv4 }} -P"
    pvrdma_service_name: "pvrdma-rping-server"

- name: "Start listening process via systemd-run on server VM"
  include_tasks: ../utils/execute_shell_cmd.yml
  vars:
    lin_shell_cmd: >
      systemd-run --unit={{ pvrdma_service_name }}
      --remain-after-exit
      {{ pvrdma_server_start_cmd }}

- name: "Pause 5 seconds to let the rping server systemd service crash if it's going to"
  ansible.builtin.pause:
    seconds: 5

- name: "Check if the rping server systemd service started successfully"
  include_tasks: ../utils/execute_shell_cmd.yml
  vars:
    lin_shell_cmd: "systemctl is-active {{ pvrdma_service_name }}"
    lin_shell_cmd_ignore_errors: true

- name: "Set fact for rping server systemd service status"
  ansible.builtin.set_fact:
    pvrdma_service_status: "{{ lin_shell_cmd_output.rc }}"

- name: "Fetch logs if the rping server systemd service failed to start or crashed"
  include_tasks: ../utils/execute_shell_cmd.yml
  vars:
    lin_shell_cmd: "journalctl -u {{ pvrdma_service_name }} --no-pager"
    lin_shell_cmd_ignore_errors: true
  when: pvrdma_service_status | int != 0

- name: "Fail with logs if the rping server systemd service failed to start or crashed"
  ansible.builtin.fail:
    msg: |
      The rping server failed to start or crashed immediately.
      Logs:
      {{ lin_shell_cmd_output.stdout }}
  when: pvrdma_service_status | int != 0