# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Take screenshots to check Windows desktop displayed after GOSC
#
- name: "Initialize the fact of Windows desktop displayed"
  ansible.builtin.set_fact:
    win_desktop_displayed: false

- name: "Set fact of the keywords to check in the screenshot files"
  ansible.builtin.set_fact:
    win_desktop_text:
      - '.*\d{1,2}\/\d{1,2}\/\d{4}.*'
      - '.*\d{1,2}:\d{2}\s*(AM|PM).*'
      - '.*Microsoft\s*Edge.*'
      - '.*Recycle\s*Bin.*'

- name: "Take VM screenshot"
  include_tasks: ../../common/vm_take_screenshot.yml
  vars:
    vm_screenshot_local_dir: "{{ current_test_log_folder }}"
    vm_screenshot_local_name: "screenshot_after_gosc_{{ retry_time }}.png"

- name: "Extract text from VM screenshot"
  when:
    - tesseract_is_installed
    - vm_screenshot_local_path
  block:
    - name: "Extract text from VM screenshot"
      include_tasks: ../../common/extract_text_from_screenshot.yml
      vars:
        local_screenshot_path: "{{ vm_screenshot_local_path }}"

    - name: "Set fact of Windows desktop displayed when date and time in extracted text list"
      ansible.builtin.set_fact:
        win_desktop_displayed: true
      when:
        - text_in_screenshot | length > 0
        - text_in_screenshot | select('search', win_desktop_text | join('|')) | list | length > 0

    - name: "Remove screenshot file"
      include_tasks: ../../common/delete_local_file.yml
      vars:
        local_path: "{{ vm_screenshot_local_path }}"
        del_local_file_ignore_errors: true
      when:
        - not win_desktop_displayed
        - retry_time not in [1, 30]
