# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for checking guest OS customization (GOSC)
# with DHCP network configuration. If VMware Tools is not installed
# and running, the test result is 'Blocked'.
# Note: VM guest OS customization requires vCenter server.
#
- name: test_gosc_workaround
  hosts: localhost
  gather_facts: false
  vars:
    gosc_network_type: "dhcp"
  tasks:
    - name: "Test code"
      ansible.builtin.set_fact:
        vm_password: "B1gd3m0z!"
        tesseract_is_installed: true

    - name: "Wait for VM IP address after GOSC"
      include_tasks: ../../common/vm_wait_guest_ip.yml
      vars:
        wait_ipv4: "{{ win_gosc_spec.gosc_ip | default('') }}"

    - name: "Update in-memory inventory after GOSC"
      include_tasks: ../utils/win_update_inventory.yml
      vars:
        always_update_inventory: true
      when: gosc_network_type == "dhcp"

    - name: "Set current test case index, name and log folder"
      include_tasks: ../../common/set_current_testcase_facts.yml
      vars:
        test_log_folder_mode: "0777"

    - name: "Try the workaround when Windows desktop display check failed"
      include_tasks: verify_desktop_display.yml
