# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   Config VMware Photon OS online repositories
#
- name: "Initialize the fact of photon_repo_configured_already"
  ansible.builtin.set_fact:
    photon_repo_configured_already: false
  when: photon_repo_configured_already is not defined

- name: "Configure Photon OS online repo"
  when: not photon_repo_configured_already
  block:
    - name: "Add VMware Photon OS online repositories"
      when: guest_os_ansible_distribution_major_ver | int <= 4
      block:
        - name: "Initialize the fact of guest OS online repositories"
          ansible.builtin.set_fact:
            guest_online_repos: []
          when: guest_online_repos is not defined

        - name: "Set fact of online repository names on {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            photon_repo_names: >-
              {{ ["photon", "photon-release", "photon-updates"]
                if (guest_os_ansible_distribution_major_ver | int) == 4
                else ["photon-release", "photon-updates"] }}

        - name: "Set fact of online repositories on {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            guest_online_repos: "{{ guest_online_repos | union([{'name': item, 'baseurl': repo_baseurl}]) }}"
          vars:
            repo_baseurl: "https://packages.broadcom.com/photon/$releasever/{{ item | replace('-', '_') }}_$releasever_$basearch"
          with_items: "{{ photon_repo_names }}"

        - name: "Update repository's baseurl"
          ansible.builtin.shell: |-
            sed -i 's#packages.vmware.com#packages.broadcom.com#g' /etc/yum.repos.d/*.repo;
            invalid_repo_files=`grep -l 'dl.bintray.com/vmware' /etc/yum.repos.d/*.repo`;
            if [ "$invalid_repo_files" != "" ] ; then
              sed -i 's#dl.bintray.com/vmware/#packages.broadcom.com/photon/$releasever/#' $invalid_repo_files;
            fi
          delegate_to: "{{ vm_guest_ip }}"
          with_items: "{{ photon_repo_names }}"

    - name: "Add Photon OS online repositories"
      when: guest_os_ansible_distribution_major_ver | int >= 5
      block:
        - name: "Get list of all photon repos"
          ansible.builtin.shell: >-
            tdnf --enablerepo=photon --disablerepo=photon-updates provides photon-repos
            | grep photon-repos
            | cut -d ':' -f 1
          delegate_to: "{{ vm_guest_ip }}"
          register: photon_repos_result

        - name: "Display all the photon repos"
          ansible.builtin.debug: var=photon_repos_result
        
        - name: "Check the repos"
          ansible.builtin.assert:
            that:
              - photon_repos_result.stdout_lines | length > 0
            fail_msg: "No Photon repos found"

        - name: "Set repo version suffix"
          ansible.builtin.set_fact:
            repo_suffix: "{{ '92' if guest_os_python_version is version('3.14', '>=') else '91' }}"

        - name: "Get the matching Photon repo packages"
          ansible.builtin.set_fact:
            photon_repo_list: >-
              {{
                photon_repos_result.stdout_lines
                | map('trim')
                | select('search', '\.' ~ repo_suffix ~ '\.ph5\.noarch$')
                | sort
                | list
              }}

        - name: "Display the matching Photon repo packages"
          ansible.builtin.debug: var=photon_repo_list
        
        - name: "Ensure the matching Photon repos exist"
          ansible.builtin.assert:
            that:
              - photon_repo_list | length > 0
            fail_msg: "There is no specified repos"

        - name: "Disable current all the repos except photon-snapshot.repo"
          ansible.builtin.shell: |
            for f in $(ls /etc/yum.repos.d/*.repo | grep -v photon-snapshot.repo); do
              sed -i 's/enabled=1/enabled=0/g' "$f";
            done
          delegate_to: "{{ vm_guest_ip }}"
          ignore_errors: true

        - name: "Install the selected Photon repo"
          ansible.builtin.command: "tdnf --enablerepo=photon update -y {{ photon_repo_list[0] }}"
          delegate_to: "{{ vm_guest_ip }}"

    - name: "Update packages metadata"
      include_tasks: repo_update.yml
    
    - name: "Set fact of photon_repo_configured_already"
      ansible.builtin.set_fact:
        photon_repo_configured_already: true


