# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Shutdown VM via executing 'poweroff' command in guest OS
#
- name: "Pause 5 seconds"
  ansible.builtin.pause:
    seconds: 5

- name: "Set fact of the 'poweroff' command"
  ansible.builtin.set_fact:
    poweroff_cmd: >-
      {%- if (guest_os_family == 'RedHat') and (guest_os_ansible_distribution_major_ver | int >= 10) -%}
      systemctl poweroff --check-inhibitors=no
      {%- else -%}poweroff
      {%- endif -%}

- name: "Shutdown guest OS"
  ansible.builtin.command: "{{ poweroff_cmd }}"
  delegate_to: "{{ vm_guest_ip }}"
  become: true
  changed_when: false
  async: 1
  poll: 0

- name: "Wait VM's power state to be powered off"
  include_tasks: ../../common/vm_wait_power_state.yml
  vars:
    expected_power_status: 'poweredOff'
    wait_power_state_timeout: 300
