# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get Ubuntu cloud image build info from /etc/cloud/build.info file
#
- name: "Initialize facts about Ubuntu cloud image build info"
  ansible.builtin.set_fact:
    cloud_image_build_info_path: "/etc/cloud/build.info"
    cloud_image_build_info_exists: false
    cloud_image_build_info: ""
    cloud_image_build_name: ""
    cloud_image_build_serial: ""

- name: "Fetch {{ cloud_image_build_info_path }} to localhost"
  include_tasks: fetch_file.yml
  vars:
    fetch_file_src_path: "{{ cloud_image_build_info_path }}"
    fetch_file_dst_path: "{{ testrun_log_path }}/"
    fetch_file_ignore_errors: true

- name: "Set fact that Ubuntu cloud image build info file exists"
  ansible.builtin.set_fact:
    cloud_image_build_info_exists: true
  when: guest_file_exists

- name: "Set fact of Ubuntu cloud image build info"
  ansible.builtin.set_fact:
    cloud_image_build_info: "{{ _build_info }}"
    cloud_image_build_name: "{{ _build_info.build_name }}"
    cloud_image_build_serial: "{{ _build_info.serial }}"
  vars:
    _build_info: "{{ lookup('file', fetch_file_local_path) | from_yaml }}"
  when: fetch_file_local_path
