# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Uninstall VMware Tools firstly when it's installed"
  include_tasks: ../wintools_uninstall_verify/uninstall_vmtools.yml
  when:
    - update_vmtools | bool
    - vmtools_is_installed

- name: "Enable test signing"
  include_tasks: enable_test_signing.yml
  when:
    - is_development_tools is defined
    - is_development_tools | bool

- name: "Initialize the date time info in guest OS"
  ansible.builtin.set_fact:
    win_date_time: ''

- name: "Get the date time info in guest OS"
  ansible.windows.win_shell: >
    (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
  delegate_to: "{{ vm_guest_ip }}"
  register: win_date_time_result

- name: "Set fact of the date time got in guest OS"
  ansible.builtin.set_fact:
    win_date_time: "{{ win_date_time_result.stdout | trim }}"
  when:
    - win_date_time_result.stdout is defined
    - win_date_time_result.stdout | trim | length != 0

- name: "Print the date time got in guest OS"
  ansible.builtin.debug: var=win_date_time

- name: "Check the date time got in guest OS"
  ansible.builtin.assert:
    that:
      - win_date_time | length != 0
    fail_msg: "Failed to get the current date time info in guest OS: {{ win_date_time }}."

- name: "Create a scheduled task to run the VMware Tools install"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
    actions:
      - path: "D:\\{{ wintools_setup_exe }}"
        arguments: '/S /v "/qn ADDLOCAL=ALL REBOOT=R"'
    triggers:
      - type: time
        start_boundary: "{{ '%Y-%m-%dT%H:%M:%S' | strftime((win_date_time | to_datetime('%Y-%m-%dT%H:%M:%S')).strftime('%s') | int + 60) }}"
        enabled: true
    username: SYSTEM
    state: present
    enabled: true
  delegate_to: "{{ vm_guest_ip }}"
  register: create_sched_task_result

- name: "Pause 5 seconds after creating VMware Tools install scheduled task"
  ansible.builtin.pause:
    seconds: 5

- name: "Set fact of getting VMware Tools install log file"
  ansible.builtin.set_fact:
    get_vmtools_install_log: true

- name: "Wait for the VMware Tools install scheduled task to finish"
  community.windows.win_scheduled_task_stat:
    name: "VMwareToolsInstall"
  delegate_to: "{{ vm_guest_ip }}"
  register: sched_task_status
  until:
    - sched_task_status is defined
    - sched_task_status.task.state.status is defined
    - sched_task_status.task.state.status != "TASK_STATE_RUNNING"
  retries: 45
  delay: 20
  failed_when: false

- name: "Display the status of scheduled task"
  ansible.builtin.debug: var=sched_task_status

- name: "Clean up the scheduled task"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
    state: absent
  delegate_to: "{{ vm_guest_ip }}"

- name: "Pause 30 seconds after VMware Tools install"
  ansible.builtin.pause:
    seconds: 30

- name: "Restart guest OS after VMware Tools install"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
