# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Uninstall VMware Tools firstly when it's installed"
  include_tasks: ../wintools_uninstall_verify/uninstall_vmtools.yml
  when:
    - update_vmtools | bool
    - vmtools_is_installed

- name: "Enable test signing"
  include_tasks: enable_test_signing.yml
  when:
    - is_development_tools is defined
    - is_development_tools | bool

- name: "Set fact of VMware Tools silent install command and getting install log file"
  ansible.builtin.set_fact:
    get_vmtools_install_log: true

- name: "Create a scheduled task to run the VMware Tools install"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
    actions:
      - path: "D:\\{{ wintools_setup_exe }}"
        arguments: '/S /v "/qn ADDLOCAL=ALL REBOOT=R"'
    username: SYSTEM
    state: present
    enabled: yes
  delegate_to: "{{ vm_guest_ip }}"
  register: create_sched_task_result

- name: "Trigger the scheduled task"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
    state: present
    sub_state: ready
  delegate_to: "{{ vm_guest_ip }}"
  register: trigger_sched_task_result

- name: "Pause 5 seconds after starting VMware Tools install task"
  ansible.builtin.pause:
    seconds: 5

- name: "Wait for the VMware Tools install scheduled task to finish"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
  delegate_to: "{{ vm_guest_ip }}"
  register: sched_task_status
  until:
    - sched_task_status is defined
    - sched_task_status.task.state.status is defined
    - sched_task_status.task.state.status != "TASK_STATE_RUNNING"
  retries: 30
  delay: 20
  failed_when: false

- name: "Display the status of scheduled task"
  ansible.builtin.debug: var=sched_task_status

- name: "Clean up the scheduled task"
  community.windows.win_scheduled_task:
    name: "VMwareToolsInstall"
    state: absent
  delegate_to: "{{ vm_guest_ip }}"

- name: "Pause 30 seconds after VMware Tools install"
  ansible.builtin.pause:
    seconds: 30

- name: "Restart guest OS after VMware Tools install"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
