# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Enable Windows Optional Feautre in guest OS.
# Parameters:
#   win_optional_feature: the Optional Feature name to be enabled in guest OS.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_optional_feature is defined
      - win_optional_feature | length != 0
    fail_msg: "Parameter 'win_optional_feature' is not set or empty: '{{ win_optional_feature | default('') }}'"

- name: "Set fact of the PowerShell commands for enabling and getting optional feature"
  ansible.builtin.set_fact:
    win_enable_optional_feature: "Enable-WindowsOptionalFeature -Online -FeatureName {{ win_optional_feature }} -All -NoRestart -WarningAction SilentlyContinue"
    win_get_optional_feature: "(Get-WindowsOptionalFeature -Online -FeatureName {{ win_optional_feature }}).State"

- name: "Execute enabling optional feature command in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "{{ win_enable_optional_feature }}"

- name: "Wait 10 seconds after enabling optional feature"
  ansible.builtin.pause:
    seconds: 10

- name: "Restart guest OS after enabling optional feature"
  include_tasks: win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"

- name: "Get optional feature state in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "{{ win_get_optional_feature }}"

- name: "Check optional feature '{{ win_optional_feature }}' installed in guest OS"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.stdout_lines is defined
      - win_powershell_cmd_output.stdout_lines | length == 1
      - win_powershell_cmd_output.stdout_lines[0].strip() in ['Installed', 'Enabled']
    fail_msg: >-
      The state of Windows optional feature '{{ win_optional_feature }}' is not 'Installed' or 'Enabled' in
      guest OS: '{{ win_powershell_cmd_output.stdout_lines | default('') }}'.
