# Copyright 2022-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get all supported guest IDs for a hardware version on ESXi server
# Parameter:
#   esxi_hardware_version: The hardware version on ESXi server, e.g. 13, 14, 15, etc.
# Return:
#   esxi_guest_ids: A list of all supported guest IDs on a hardware version

- name: "Check esxi_hardware_version is set with valid value"
  ansible.builtin.assert:
    that:
      - esxi_hardware_version is defined
      - esxi_hardware_version is match('^\d+')
    fail_msg: "Incorrect hardware version '{{ esxi_hardware_version }}'"

- name: "Initialize ESXi server supported guest IDs on hardware version {{ esxi_hardware_version }}"
  ansible.builtin.set_fact:
    esxi_guest_ids: []

 - name: "Set default method for getting ESXi server supported guest IDs"
   ansible.builtin.set_fact:
    get_method: >-
      {%- if esxi_version is match('7.0.*') -%}xml
      {%- elif esxi_latest_hardware_version | int < esxi_hardware_version | int -%}xml
      {%- else -%}api
      {%- endif -%}

- name: "Get ESXi server supported guest IDs via the API"
  when: get_method == 'api'
  block:
    - name: "Get ESXi server supported guest IDs on hardware version {{ esxi_hardware_version }}"
      community.vmware.vmware_vm_config_option:
        hostname: "{{ vsphere_host_name }}"
        username: "{{ vsphere_host_user }}"
        password: "{{ vsphere_host_user_password }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ vsphere_host_datacenter }}"
        esxi_hostname: "{{ esxi_hostname }}"
        get_guest_os_ids: true
        hardware_version: "vmx-{{ esxi_hardware_version }}"
      register: get_guest_os_ids_result

    - name: "Check ESXi server supported guest IDs are retrieved via the API"
      ansible.builtin.assert:
        that:
          - get_guest_os_ids_result is defined
          - get_guest_os_ids_result.instance is defined
          - get_guest_os_ids_result.instance | length > 0
        fail_msg: >-
          Failed to get ESXi server supported guest IDs on hardware version {{ esxi_hardware_version }}
          via the API

    - name: "Set fact of ESXi server supported guest IDs for hardware version {{ esxi_hardware_version }}"
      ansible.builtin.set_fact:
        esxi_guest_ids: "{{ get_guest_os_ids_result.instance | dict2items | map(attribute='value') | flatten }}"

- name: "Get ESXi server supported guest IDs from the XML configuration file"
  when: get_method == 'xml'
  block:
    - name: "Initialize variables for getting hardware version supported guest IDs"
      ansible.builtin.set_fact:
        vm_config_option_esx_hw: "/etc/vmware/hostd/env/vmconfigoption-esx-hw{{ esxi_hardware_version }}.xml"
        vm_default_config_xpath: "/ConfigRoot/ConfigurationOption/guestOSDescriptor/e/id"

    - name: "Get hardware version {{ esxi_hardware_version }} supported guest IDs on ESXi server"
      community.general.xml:
        path: "{{ vm_config_option_esx_hw }}"
        xpath: "{{ vm_default_config_xpath }}"
        content: text
        pretty_print: true
      delegate_to: "{{ esxi_hostname }}"
      register: guest_os_desc_ids_result

    - name: "Set fact of ESXi server supported guest IDs for hardware version {{ esxi_hardware_version }}"
      ansible.builtin.set_fact:
        esxi_guest_ids: "{{ guest_os_desc_ids_result.matches | map(attribute='id') | list }}"

- name: "Print ESXi server supported guest IDs on hardware version {{ esxi_hardware_version }}"
  ansible.builtin.debug: var=esxi_guest_ids
