# Copyright 2022-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get default VM config options for a specific guest ID
# Parameters:
#   guest_id: The VM's guest ID
#   esxi_hardware_version: The ESXi hardware version supporting the guest ID
# Return:
#   guest_config_options: The guest ID config options on a hardware version
# Example output:
#  "guest_config_options": {
#      "default_cdrom_controller": "sata",
#      "default_disk_controller": "paravirtual",
#      "default_ethernet": "vmxnet3",
#      "default_secure_boot": true,
#      "default_usb_controller": "",
#      "guest_fullname": "Red Hat Enterprise Linux 9 (64-bit)",
#      "guest_id": "rhel9_64Guest",
#      "hardware_version": "vmx-19",
#      "rec_cpu_cores_per_socket": 1,
#      "rec_cpu_socket": 1,
#      "rec_disk_mb": 16384,
#      "rec_firmware": "efi",
#      "rec_memory_mb": 2048,
#      "rec_persistent_memory": 8192,
#      "rec_vram_kb": 8192,
#      "support_cpu_hotadd": true,
#      "support_disk_controller": [
#          "paravirtual",
#          "sata",
#          "nvme",
#          "ide"
#      ],
#      "support_ethernet_card": [
#          "vmxnet3",
#          "e1000e",
#          "sriov",
#          "pvrdma"
#      ],
#      "support_for_create": true,
#      "support_memory_hotadd": true,
#      "support_min_persistent_mem_mb": 4,
#      "support_persistent_memory": true,
#      "support_secure_boot": true,
#      "support_tpm_20": true,
#      "support_usb_controller": [
#          "usb2",
#          "usb3"
#      ]
#  }
#
- name: "Set default method for getting VM default config options"
   ansible.builtin.set_fact:
    get_method: >-
      {%- if esxi_version is match('7.0.*') -%}xml
      {%- elif esxi_latest_hardware_version | int < esxi_hardware_version | int -%}xml
      {%- else -%}api
      {%- endif -%}

- name: "Check esxi_hardware_version is set with valid value"
  ansible.builtin.assert:
    that:
      - esxi_hardware_version is defined
      - esxi_hardware_version is match('^\d+')
    fail_msg: "Incorrect parameters: esxi_hardware_version={{ esxi_hardware_version | default('') }}"

- name: "Initialize the guest config options dict"
  ansible.builtin.set_fact:
    guest_config_options: {}

- name: "Get VM default config options from API"
  include_tasks: esxi_get_guest_config_options_from_api.yml
  when: get_method == "api"

- name: "Get VM default config options from XML"
  include_tasks: esxi_get_guest_config_options_from_xml.yml
  when: get_method == "xml"

- name: "Set default CPU number for VM with guest ID {{ guest_id }}"
  ansible.builtin.set_fact:
    guest_config_options: >-
      {{
        guest_default_config_options |
        combine({
                 'default_cpu_number':
                 (guest_default_config_options.rec_cpu_cores_per_socket | int) * (guest_default_config_options.rec_cpu_socket | int)
                })
       }}
  when:
    - guest_default_config_options is defined
    - guest_default_config_options.rec_cpu_cores_per_socket | default('')
    - guest_default_config_options.rec_cpu_cores_per_socket | int >= 1
    - guest_default_config_options.rec_cpu_socket | default('')
    - guest_default_config_options.rec_cpu_socket | int >= 1

- name: "Display guest ID {{ guest_id }} config options on hardware version {{ esxi_hardware_version }} get from {{ get_method }}"
  ansible.builtin.debug: var=guest_config_options
