# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Extract VM default config options for a specific Guest ID from the XML configuration file.
# Parameters:
#   guest_id: The VM's guest ID
#   esxi_hardware_version: The ESXi hardware version supporting the guest ID
# Return:
#   guest_default_config_options: The guest ID default config options on a hardware version
#
- name: "Initialize the guest default config options dict"
  ansible.builtin.set_fact:
    guest_default_config_options: {}

- name: "Initialize variables for getting guest ID default configs"
  ansible.builtin.set_fact:
    esxi_vm_config_option_file: "/etc/vmware/hostd/env/vmconfigoption-esx-hw{{ esxi_hardware_version }}.xml"
    local_vm_config_option_file: "{{ local_cache }}/vmconfigoption-esx-hw{{ esxi_hardware_version }}.xml"
    vm_device_types:
      vim.vm.device.VirtualLsiLogicController: 'lsilogic'
      vim.vm.device.VirtualLsiLogicSASController: 'lsilogicsas'
      vim.vm.device.ParaVirtualSCSIController: 'paravirtual'
      vim.vm.device.VirtualAHCIController: 'sata'
      vim.vm.device.VirtualNVMEController: 'nvme'
      vim.vm.device.VirtualIDEController: 'ide'
      vim.vm.device.VirtualBusLogicController: 'buslogic'
      vim.vm.device.VirtualVmxnet3: 'vmxnet3'
      vim.vm.device.VirtualE1000e: 'e1000e'
      vim.vm.device.VirtualE1000: 'e1000'
      vim.vm.device.VirtualVmxnet3Vrdma: 'pvrdma'
      vim.vm.device.VirtualSriovEthernetCard: 'sriov'
      vim.vm.device.VirtualPCNet32: 'pcnet32'
      vim.vm.device.VirtualVmxnet2: 'vmxnet2'
      vim.vm.device.VirtualVmxnet: 'vmxnet'
      vim.vm.device.VirtualUSBController: 'usb2'
      vim.vm.device.VirtualUSBXHCIController: 'usb3'
    vm_config_name:
      id: "guest_id"
      recommendedCdromController: "default_cdrom_controller"
      numRecommendedCoresPerSocket: "rec_cpu_cores_per_socket"
      numRecommendedPhysicalSockets: "rec_cpu_socket"
      recommendedUSBController: "default_usb_controller"
      recommendedDiskController: "default_disk_controller"
      recommendedDiskSizeMB: "rec_disk_mb"
      recommendedFirmware: "rec_firmware"
      recommendedMemMB: "rec_memory_mb"
      recommendedEthernetCard: "default_ethernet"
      defaultSecureBoot: "default_secure_boot"
      supportsSecureBoot: "support_secure_boot"
      fullName: "guest_fullname"
      vRAMSizeInKB: "rec_vram_kb"
      supportsCpuHotAdd: "support_cpu_hotadd"
      supportsMemoryHotAdd: "support_memory_hotadd"
      supportedForCreate: "support_for_create"
      recommendedPersistentMemoryMB: "rec_persistent_memory"
      supportedMinPersistentMemoryMB: "support_min_persistent_mem_mb"
      persistentMemorySupported: "support_persistent_memory"
      supportsTPM20: "support_tpm_20"
      supportedDiskControllerList: "support_disk_controller"
      supportedEthernetCard: "support_ethernet_card"
      supportedUSBControllerList: "support_usb_controller"

- name: "Initialize VM default config options"
  ansible.builtin.set_fact:
    guest_default_config_options: >-
      {{
        vm_config_name.values() | zip_longest([], fillvalue='') |
        items2dict(key_name=0, value_name=1) |
        combine({'hardware_version': 'vmx-' ~  esxi_hardware_version})
      }}

- name: "Fetch config option file from ESXi server"
  ansible.builtin.fetch:
    src: "{{ esxi_vm_config_option_file }}"
    dest: "{{ local_vm_config_option_file }}"
    flat: true
  delegate_to: "{{ esxi_hostname }}"

- name: "Set fact of overall guest config options"
  ansible.builtin.set_fact:
    guest_os_descriptor: >-
      {{
        _all_guest_config_options.ConfigRoot.ConfigurationOption.guestOSDescriptor.e |
        selectattr('id', 'equalto', guest_id)
      }}
  when:
    - _all_guest_config_options.ConfigRoot.ConfigurationOption.guestOSDescriptor.e is defined
    - _all_guest_config_options.ConfigRoot.ConfigurationOption.guestOSDescriptor.e | length > 0
  vars:
    _all_guest_config_options: "{{ lookup('file', local_vm_config_option_file) | ansible.utils.from_xml }}"

- name: "Check guest ID {{ guest_id }} has guest config options on hardware version {{ esxi_hardware_version }}"
  ansible.builtin.assert:
    that:
      - guest_os_descriptor | length > 0
    fail_msg: >-
      Failed to find guest config options for guest ID {{ guest_id }} with
      hardware version {{ esxi_hardware_version }}

- name: "Set fact of VM default config options for guest ID {{ guest_id }}"
  ansible.builtin.set_fact:
    guest_default_config_options: >-
      {{
        guest_default_config_options |
        combine({vm_config_name[item.key]: (_value is match('\d+')) | ternary(_value | int, _value) })
      }}
  vars:
    _value: >-
       {%- if item.value in ['true', 'false'] -%}{{ item.value | bool }}
       {%- elif item.value in vm_device_types -%}{{ vm_device_types[item.value] }}
       {%- elif item.key == 'fullName' and 'Arm' in item.value -%}{{ item.value | replace(' Arm', '') }}
       {%- else -%}{{ item.value }}
       {%- endif -%}
  when:
    - item.key in vm_config_name
    - item.value | type_debug not in ["list", "dict"]
  with_dict: "{{ guest_os_descriptor[0] }}"

- name: "Set fact of VM default config options for guest ID {{ guest_id }}"
  ansible.builtin.set_fact:
    guest_default_config_options: >-
      {{
        guest_default_config_options |
        combine({'rec_vram_kb': guest_os_descriptor[0].vRAMSizeInKB.defaultValue | int})
      }}
  when:
    - guest_os_descriptor[0].vRAMSizeInKB.defaultValue is defined
    - guest_os_descriptor[0].vRAMSizeInKB.defaultValue is match('\d+')

# If the supported device list has only one item,  the 'e' element will be a dictionary
# If the supported device list has more than one item, the 'e' element will be a list
- name: "Set supported device lists for guest ID {{ guest_id }}"
  ansible.builtin.set_fact:
    guest_default_config_options: >-
      {{
        guest_default_config_options |
        combine({
                 vm_config_name[item]:
                 _supported_device_list | map('extract', vm_device_types) | list
                })
       }}
  vars:
    _supported_device_list: >-
       {{
         (guest_os_descriptor[0][item].e | type_debug == 'dict') |
         ternary([guest_os_descriptor[0][item].e['#text']],
                 guest_os_descriptor[0][item].e |
                 selectattr('#text', 'defined') |
                 map(attribute='#text'))
       }}
  when:
    - guest_os_descriptor[0][item].e is defined
    - guest_os_descriptor[0][item].e | length > 0
  with_items:
    - "supportedDiskControllerList"
    - "supportedEthernetCard"
    - "supportedUSBControllerList"

- name: "Remove VM config option file at local cache"
  ansible.builtin.file:
    path: "{{ local_vm_config_option_file }}"
    state: absent

- name: "Display guest ID {{ guest_id }} default config options on hardware version {{ esxi_hardware_version }} from XML"
  ansible.builtin.debug: var=guest_default_config_options
