# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# The prerequsite of adding virtual TPM device to VM is key provider
# configured on vCenter server. This task file is used for adding
# standard or native key provider when there is no default key provider
# configured on vCenter server. 
#
- name: "Get existing key provider on vCenter"
  include_tasks: vcenter_get_key_provider.yml

- name: "Skip adding new key provider"
  ansible.builtin.debug:
    msg: "Skip adding new key provider since there is default one already configured."
  when: has_default_key_provider

- name: "Add new key provider when there is no default one"
  when: not has_default_key_provider
  block:
    - name: "Set fact of the key provider type"
      ansible.builtin.set_fact:
        key_provider_type: "{{ key_provider_type | lower }}"
      when: key_provider_type is defined

    - name: "Set fact of the key provider type according to ESXi and vCenter versions"
      ansible.builtin.set_fact:
        key_provider_type: >-
          {%- if esxi_version is version('7.0.3', '>=') and vcenter_version is version('7.0.3', '>=') -%}native
          {%- else -%}standard
          {%- endif -%}
      when: key_provider_type is undefined

    - name: "Display key provider type"
      ansible.builtin.debug: var=key_provider_type

    - name: "Check key provider type"
      ansible.builtin.assert:
        that:
          - key_provider_type in ['standard', 'native']
        fail_msg: "Parameter 'key_provider_type' is set to '{{ key_provider_type }}', which is not expected 'standard' or 'native'."

    - name: "Set fact of new key provider name"
      ansible.builtin.set_fact:
        new_kp_name: "{{ key_provider_type }}{{ current_test_timestamp }}"

    - name: "Add standard key provider on vCenter server"
      include_tasks: vcenter_add_standard_kp.yml
      vars:
        standard_kp_name: "{{ new_kp_name }}"
      when: key_provider_type == 'standard'

    - name: "Add native key provider on vCenter server"
      include_tasks: vcenter_add_native_kp.yml
      vars:
        native_kp_name: "{{ new_kp_name }}"
      when: key_provider_type == 'native'

    - name: "Set fact of key provider has been added on vCenter server"
      ansible.builtin.set_fact:
        key_provider_added: true
