# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Setup vSphere Distributed Switch (VDS) networking, include:
#   - Create a new vSphere Distributed Switch
#   - Create a new distributed port group
#   - Add ESXi host to the vSphere Distributed Switch
#   - Add a VMkernel network adapter on the ESXi host and assign with distributed port group
#
- name: "Get the vSphere Distributed Switch info on ESXi host"
  include_tasks: esxi_get_vds_info.yml

- name: "Check the number of vSphere Distributed Switch on ESXi host"
  ansible.builtin.assert:
    that:
      - get_host_vds_result.distributed_virtual_switches is defined
      - get_host_vds_result.distributed_virtual_switches | length < 15
    fail_msg: >-
      There are already '{{ get_host_vds_result.distributed_virtual_switches | length }}' vSphere Distributed Switch
      connected by ESXi host '{{ esxi_hostname }}', please remove any unused ones to adhere to the recommended maximum of 16.
      Exceeding this value can lead to unexpected behavior and is generally not a supported configuration.

- name: "Set facts of the network environment"
  ansible.builtin.set_fact:
    network_env_net_mask: "255.255.255.0"
    network_env_net_prefix: 24

- name: "Generate a random number between 1000 to 9999"
  ansible.builtin.set_fact:
    vds_random_number: "{{ range(1000, 10000) | ansible.builtin.random }}"

- name: "Set facts of the new vSphere Distributed Switch and Port Group names"
  ansible.builtin.set_fact:
    vds_name: "DSwitch{{ testrun_timestamp }}-{{ vds_random_number }}"
    vds_portgroup_name: "DPortGroup{{ testrun_timestamp }}-{{ vds_random_number }}"

- name: "Create a new vSphere Distributed Switch '{{ vds_name }}'"
  include_tasks: vcenter_manage_vds.yml
  vars:
    vds_state: "present"

- name: "Create a new distributed port group '{{ vds_portgroup_name }}'"
  include_tasks: vcenter_manage_vds_portgroup.yml
  vars:
    vds_portgroup_state: "present"

- name: "Add ESXi host to the vSphere Distributed Switch '{{ vds_name }}'"
  include_tasks: vcenter_manage_vds_host.yml
  vars:
    vds_host_state: "present"

- name: "Add a new VMkernel network adapter on the ESXi host '{{ esxi_hostname }}'"
  include_tasks: esxi_manage_vmkernel_adapter.yml
  vars:
    vmk_state: "present"
    vmk_vds_name: "{{ vds_name }}"
    vmk_portgroup_name: "{{ vds_portgroup_name }}"
    vmk_network:
      type: 'static'
      ip_address: '169.254.254.254'
      subnet_mask: '255.255.255.0'
    vmk_enable_mgmt: false

- name: "Set fact of new created VMkernel network adapter device name"
  ansible.builtin.set_fact:
    vds_vmk_device_name: "{{ manage_vmk_result.device | default('') }}"

- name: "Check the newly created VMkernel network adapter device name"
  ansible.builtin.assert:
    that:
      - vds_vmk_device_name is match('^vmk\d+$')
    fail_msg: "Failed to get VMkernel network adapter device '{{ vds_vmk_device_name }}' on ESXi host '{{ esxi_hostname }}'."
    success_msg: "Successfully got VMkernel network adapter device '{{ vds_vmk_device_name }}' on ESXi host '{{ esxi_hostname }}'."

- name: "Set fact of the index of the newly created VMkernel network adapter"
  ansible.builtin.set_fact:
    vds_vmk_device_index: "{{ vds_vmk_device_name | regex_search('(\\d+)$') | int }}"
  
- name: "Set fact of the IP address of the newly created VMkernel network adapter"
  ansible.builtin.set_fact:
    vds_vmk_ip_addr: "192.168.{{ vds_vmk_device_index | int }}.1"

- name: "Set fact of the network info for the newly created VMkernel network adapter"
  ansible.builtin.set_fact:
    vds_vmk_network:
      type: 'static'
      ip_address: "{{ vds_vmk_ip_addr }}"
      subnet_mask: "{{ network_env_net_mask }}"
      default_gateway: "{{ vds_vmk_ip_addr }}"

- name: "Configure network for the newly created VMkernel network adapter"
  include_tasks: esxi_manage_vmkernel_adapter.yml
  vars:
    vmk_state: "present"
    vmk_device: "{{ vds_vmk_device_name }}"
    vmk_vds_name: "{{ vds_name }}"
    vmk_portgroup_name: "{{ vds_portgroup_name }}"
    vmk_network: "{{ vds_vmk_network }}"
    vmk_enable_mgmt: false

- name: "Check the result of configuring network for the newly created VMkernel network adapter"
  ansible.builtin.assert:
    that:
      - manage_vmk_result.device is defined
      - manage_vmk_result.device == vds_vmk_device_name
      - manage_vmk_result.ipv4_ip is defined
      - manage_vmk_result.ipv4_ip == vds_vmk_ip_addr
    fail_msg: "Failed to configure network for VMkernel network adapter '{{ vds_vmk_device_name }}' on ESXi host '{{ esxi_hostname }}'."
    success_msg: "Successfully configured network for VMkernel network adapter '{{ vds_vmk_device_name }}' on ESXi host '{{ esxi_hostname }}'."

- name: "Set facts of the vSphere Distributed Switch network"
  ansible.builtin.set_fact:
    vds_network_is_setup: true
    network_env_gateway: "{{ vds_vmk_ip_addr }}"
    network_env_net_name: "{{ vds_portgroup_name }}"
    network_env_nic_ip: "{{ vds_vmk_ip_addr | ansible.utils.ipmath(10) }}"