# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Remove specified VM snapshot or remove all snapshots of VM
# Parameters:
#   snapshot_remove_all: can be set to true or false (default)
#   snapshot_name:
#     if snapshot_remove_all is set to true, then it's not required,
#     if snapshot_remove_all is set to false, then it's required to pass an existing snapshot name
#
- name: "Remove snapshot on '{{ vm_name }}'"
  vmware.vmware.vm_snapshot:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    datacenter: "{{ vsphere_host_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: absent
    remove_all: "{{ (snapshot_remove_all | default(false)) | bool }}"
    snapshot_name: "{{ omit if ((snapshot_remove_all | default(false)) | bool) else snapshot_name | default(omit) }}"
  register: task_result

- name: Display the result of remove snapshot
  ansible.builtin.debug: var=task_result
  when: enable_debug is defined and enable_debug

- name: "Check if the snapshot '{{ snapshot_name }}' is removed"
  when: not ((snapshot_remove_all | default(false)) | bool)
  block:
    - name: "Get VM's snapshots"
      include_tasks: vm_get_snapshot_facts.yml

    - name: "Assert snapshot '{{ snapshot_name }}' not exist"
      ansible.builtin.assert:
        that:
          - item.name != snapshot_name
        fail_msg: "Failed to remove snapshot {{ snapshot_name }}"
      with_items: "{{ vm_snapshot_facts.guest_snapshots.snapshots }}"
      when: vm_snapshot_facts.guest_snapshots | length > 0
