# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Revert to the specified snapshot of VM. Please get VM snapshots info
# and check if specified snapshot exists firstly before using this task file.
# Parameters:
#   snapshot_name: the name of snapshot to revert.
#
- name: "Check snapshot name is not empty"
  ansible.builtin.assert:
    that:
      - snapshot_name is defined
      - snapshot_name | length > 0
    fail_msg: "The parameter 'snapshot_name' is not defined or is empty."

- name: "Revert to snapshot {{ snapshot_name }}"
  vmware.vmware.vm_snapshot_revert:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    datacenter: "{{ vsphere_host_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    snapshot_name: "{{ snapshot_name }}"
  register: revert_result

- name: "Display revert snapshot result"
  ansible.builtin.debug: var=revert_result
  when: enable_debug

- name: "Wait for VM current snapshot is as expected after reverting"
  include_tasks: vm_wait_expected_snapshot.yml
  vars:
    expected_snapshot_name: "{{ snapshot_name }}"
