# Copyright 2025-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Rebuild FreeBSD ISO image with unattended install file
# Parameters:
#   rebuilt_unattend_iso_path: Local path to the rebuilt ISO image with unattend install config file
#   src_iso_file_path: Local path to the source ISO image file
#   src_iso_dir_path: Local path to the directory containing the source ISO image file.
#

- name: "Set fact of temporary directory for extracted FreeBSD ISO contents"
  ansible.builtin.set_fact:
    extracted_freebsd_iso_dir: "{{ src_iso_dir_path }}/freebsd_iso_extracted"

- name: "Rebuild FreeBSD unattended install ISO block"
  block:
    - name: "Create temporary directory for extracted FreeBSD ISO"
      ansible.builtin.file:
        path: "{{ extracted_freebsd_iso_dir }}"
        state: directory
        mode: '0755'

    - name: "Extract FreeBSD ISO using xorriso"
      ansible.builtin.command: >-
        xorriso -osirrox on -indev "{{ src_iso_file_path }}" -extract / "{{ extracted_freebsd_iso_dir }}"
      changed_when: true

    - name: "Ensure extracted files and directories are writable"
      ansible.builtin.command: >-
        chmod -R u+w "{{ extracted_freebsd_iso_dir }}"
      changed_when: true

    - name: "Copy installerconfig to extracted FreeBSD ISO"
      ansible.builtin.copy:
        src: "{{ new_unattend_install_conf }}"
        dest: "{{ extracted_freebsd_iso_dir }}/etc/installerconfig"
        mode: '0644'

    - name: "Update boot loader option for 32bit FreeBSD autoinstall"
      ansible.builtin.lineinfile:
        path: "{{ extracted_freebsd_iso_dir }}/boot/loader.conf"
        line: 'kern.kstack_pages="8"'
        create: true
        mode: '0644'
      when: "'64Guest' not in guest_id"

    - name: "Check if EFI boot image exists in FreeBSD ISO"
      ansible.builtin.stat:
        path: "{{ extracted_freebsd_iso_dir }}/boot/efiboot.img"
      register: freebsd_efiboot_img

    - name: "Set xorriso boot options for FreeBSD ISO"
      ansible.builtin.set_fact:
        xorriso_boot_options: >-
          -b boot/cdboot -no-emul-boot
          {% if freebsd_efiboot_img.stat.exists %}-eltorito-alt-boot -e boot/efiboot.img -no-emul-boot{% endif %}

    - name: "Rebuild ISO image file for FreeBSD using xorriso"
      ansible.builtin.command: >-
        xorriso -as mkisofs -R -J -V "FREEBSD_INSTALL"
        {{ xorriso_boot_options }}
        -o "{{ rebuilt_unattend_iso_path }}"
        "{{ extracted_freebsd_iso_dir }}"
      changed_when: true
  always:
    - name: "Clean up extracted FreeBSD ISO directory"
      ansible.builtin.file:
        path: "{{ extracted_freebsd_iso_dir }}"
        state: absent
