# Copyright 2025-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Test snapshot task and won't be committed
#
- name: test_snaphot
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test setup"
      include_tasks: ../setup/test_setup.yml
      vars:
        create_test_log_folder: true

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    # reset_base_snapshot.yml will test remove, rename and take snapshot
    - name: "Take a new snapshot and set it as base snapshot"
      include_tasks: ../../common/reset_base_snapshot.yml

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Take a snapshot 1"
      include_tasks: ../../common/vm_take_snapshot.yml
      vars:
        snapshot_name: "snapshot_1"
    
    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20
  
    - name: "Take a snapshot 2"
      include_tasks: ../../common/vm_take_snapshot.yml
      vars:
        snapshot_name: "snapshot_2"
    
    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Remove all snapshot"
      include_tasks: ../../common/vm_remove_snapshot.yml
      vars:
        snapshot_remove_all: true

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Take a snapshot 3"
      include_tasks: ../../common/vm_take_snapshot.yml
      vars:
        snapshot_name: "snapshot_3"
    
    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Take a snapshot 4"
      include_tasks: ../../common/vm_take_snapshot.yml
      vars:
        snapshot_name: "snapshot_4"
        snapshot_description: "snapshot_4_description"

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Rename snapshot snapshot_4 to snapshot_44 and modify description"
      include_tasks: vm_rename_snapshot.yml
      vars:
        current_snapshot_name: "snapshot_4"
        new_snapshot_name: "snapshot_44"
        new_snapshot_description: "4444"

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Rename snapshot to snapshot_44 to snapshot_55 and don't modify description"
      include_tasks: vm_rename_snapshot.yml
      vars:
        current_snapshot_name: "snapshot_44"
        new_snapshot_name: "snapshot_55"

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Revert snapshot to snapshot_3"
      include_tasks: ../common/vm_revert_snapshot.yml
      vars:
        snapshot_name: "snapshot_3"
        skip_if_not_exist: true

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

    - name: "Revert snapshot to non-existing snapshot"
      include_tasks: ../common/vm_revert_snapshot.yml
      vars:
        snapshot_name: "snapshot_1"
        skip_if_not_exist: false

    - name: "Sleep 20 seconds to abserve the changes"
      ansible.builtin.pause:
        seconds: 20

